[project]
name = "todo-bene"
version = "0.1.0"
description = "To-do-list"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.3",
    "pendulum[test]>=3.1.0",
    "typer>=0.21.0",
]

[dependency-groups]
dev = [
    "bandit>=1.9.2",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "radon>=6.0.1",
    "ruff>=0.14.13",
]
[project.scripts]
tb = "todo_bene.infrastructure.cli.main:app"

[tool.uv]
package = true

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["todo_bene*"]